#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
AXIOM_PATH="$(dirname "$SCRIPT_DIR")" # Assumes axiom-account-setup is in interact/
source "$AXIOM_PATH/interact/includes/vars.sh"

echo -e "${BWhite}Axiom Account Setup${Color_Off}"
echo -e "${BGreen}You can use this wizard to add new accounts, once made, use axiom-account to switch between profiles${Color_Off}"

# Get the list of account helpers
account_helpers=$(find "$AXIOM_PATH/interact/account-helpers" -name "*.sh" -exec basename -s '.sh' {} + | sort -u)
account_str=$(echo $account_helpers | sed 's/ /, /g')
echo -e -n "${Green}Please enter your provider ($account_str): \n>> ${Color_Off}"
read -e provider
provider_path="$AXIOM_PATH/interact/account-helpers/$provider.sh"
# For all other providers, check if the provider file exists
while [[ ! -f "$provider_path" ]]; do
 echo -e -n "${Green}This is not a valid provider, please enter a valid provider ($account_str): \n>> ${Color_Off}"
 read -e provider
 provider_path="$AXIOM_PATH/interact/account-helpers/$provider.sh"
done

# Finally, execute the provider's script
bash "$provider_path"
