#!/bin/bash

AXIOM_PATH="$HOME/.axiom"
provider="$(jq -r '.provider' "$AXIOM_PATH"/axiom.json)"
source "$AXIOM_PATH/interact/includes/vars.sh"
source "$AXIOM_PATH/interact/includes/functions.sh"
account_path=$(ls -la $AXIOM_PATH/axiom.json | rev | cut -d " " -f 1 | rev)

if [ "$1" == "ls" ]
then
	list_regions
elif [ "$1" == "select" ]
then
	region_json=$(regions)
	lines=$(echo $region_json | grep "$2" | wc -l | awk '{ print $1 }')

	if [ "$lines" -gt 0 ]
	then
		cat $AXIOM_PATH/axiom.json | jq -r ".region=\"$2\"" | jq -r > $AXIOM_PATH/axiom.json.new
		if [ "$provider" = "gcp" ]; then
			physical_region=$(echo $2| rev | cut -d '-' -f2- | rev)
			availability_zones=$(echo "$region_json" | jq -r '.[].name')
			# Check if selected availability zone is in the list of valid availability zones
			if ! echo "$2" | grep -qw "$availability_zones"; then
				echo -e "${BRed}Error: for GCP you must select an availability zone as a region${Color_Off}"
				echo -e "${BRed}List all availability zones with ax region ls.. exiting${Color_Off}"
				exit
			fi
			cat $AXIOM_PATH/axiom.json | jq -r ".physical_region=\"$physical_region\"" | jq -r ".region=\"$2\"" |jq -r > $AXIOM_PATH/axiom.json.new
		fi


                if [ "$provider" = "aws" ]; then
                        # Get AWS profile option from axiom.json
                        aws_profile=$(jq -r '.aws_profile // empty' "$AXIOM_PATH/axiom.json" 2>/dev/null)
                        if [[ -n "$aws_profile" && "$aws_profile" != "null" ]]; then
                                aws configure set region $2 --profile "$aws_profile"
                        else
                                aws configure set region $2
                        fi
                fi


	mv $AXIOM_PATH/axiom.json.new $account_path
	echo -e "${BWhite}Selected region $2${Color_Off}"
	fi
else
        echo -e "${BWhite}Usage:${Color_Off} axiom-region [COMMAND]"
        echo
        echo -e "${BWhite}Description:${Color_Off}"
        echo -e "  List or select the default region used for instance creation."
        echo
        echo -e "${BWhite}Commands:${Color_Off}"
        echo -e "  ls                         List all available regions for the current provider"
        echo -e "  select <region>            Set the default region (e.g. nyc3, us-west, eu-central)"
        echo
        echo -e "${BWhite}Examples:${Color_Off}"
        echo -e "  ${BGreen}axiom-region ls${Color_Off}                              # Show all available regions"
        echo -e "  ${BGreen}axiom-region select nyc3${Color_Off}                     # Set 'nyc3' as the default region"
        echo
fi
