#!/bin/bash

ip=$(ip -4 addr show scope global | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | grep -vE '^10\.|^172\.(1[6-9]|2[0-9]|3[01])\.|^192\.168\.')
echo ""
cat << EOF
 █████╗ ██╗  ██╗
██╔══██╗╚██╗██╔╝
███████║ ╚███╔╝ 
██╔══██║ ██╔██╗ 
██║  ██║██╔╝ ██╗
╚═╝  ╚═╝╚═╝  ╚═╝

EOF
echo ""
echo -e "Public IP: \033[0;34m$ip\033[0m - Instance: \033[0;34m$(hostname)\033[0m"
echo ""
